[package]
name = "flusty-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flusty-parse = { path = "../parser" }
log = "0.4.17"
serde = { version = "1.0.163", features = ["derive"] }
simplelog = "0.12.1"
toml = "0.7.4"
